### ISSUE TITLE
podman 5.8.7: copying an archive into a container fails with "path escapes from parent" when the path crosses an absolute symlink such as /var/run

### ISSUE THREAD

**Issue by skymoo** [podman-container-tools/podman#29805]
### Issue Description

Since 5.8.7, extracting an archive into a container fails when an entry's path passes through an absolute symlink inside the container filesystem. The common case is `/var/run -> /run`, which Debian and Ubuntu based images ship. The error is:

```
copying to container: statat var/run/<name>: path escapes from parent
```

This looks like a side effect of the CVE-2026-79705 fix in buildah/copier (GHSA-3528-5p26-cf44, buildah v1.43.4, pulled in by 5.8.7): path operations now run under a sandboxed root, which refuses to follow absolute symlinks even when the target is inside the container root.

`podman cp <file> ctr:/var/run/x` still works, because the CLI resolves the destination path inside the container before copying. Clients that send an archive with the path already in the entry names, extracted at `/`, do not get that resolution. The Docker-compatible `PUT /containers/{id}/archive` API is the main way this is hit: the Forgejo Actions runner (and act) copies every action into the job container this way under `/var/run/act/...`, so on podman 5.8.7 every job fails at checkout with the error above in the runner log:

```
failed to copy directory "/data/.cache/act/<hash>/" to container: Error response from daemon: statat var/run/act/actions/<hash>/.git: path escapes from parent
```

Docker had the same regression from its own os.Root hardening in 29.5.1 and fixed it in 29.5.2 by resolving in-container symlinks before the sandboxed operations: https://github.com/moby/moby/pull/52655 (see also https://code.forgejo.org/forgejo/runner/issues/1524 for the runner-side reports).

### Steps to reproduce the issue

```
podman run -d --rm --name t docker.io/library/node:26.9.0-trixie sleep 120
echo hi > /tmp/x
tar -C /tmp --transform 's,^x,var/run/x,' -cf - x | podman cp - t:/
```

For comparison, `podman cp /tmp/x t:/var/run/x` succeeds on the same container, and an image where `/var/run` is a relative symlink (`node:26.9.0-alpine` has `/var/run -> ../run`) is not affected.


### Describe the results you received

```
Error: 1 error occurred:
        * copying to container: statat var/run/x: path escapes from parent
```

Same result rootless (above) and rootful via the API socket (Forgejo runner)

### Describe the results you expected

The file lands in `/run/x` inside the container, as it did on 5.8.4. Absolute symlinks whose target stays inside the container root should be followed; only escapes from the container root should be rejected.

### podman info output

```yaml
Taken on a sibling host running the same Fedora bootc image with podman 5.8.7 (the runner host is currently rolled back to the previous image build, which has podman 5.8.4 and buildah 1.43.2, to keep CI working; nothing else differs between the two builds).


host:
  arch: amd64
  buildahVersion: 1.43.4
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.2.1-2.fc44.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.2.1, commit: '
  cpuUtilization:
    idlePercent: 99.33
    systemPercent: 0.27
    userPercent: 0.4
  cpus: 2
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    version: "44"
  emulatedArchitectures:
  - linux/arm
  - linux/arm64
  - linux/arm64be
  - linux/loong64
  - linux/mips
  - linux/mips64
  - linux/ppc
  - linux/ppc64
  - linux/ppc64le
  - linux/riscv32
  - linux/riscv64
  - linux/s390x
  eventLogger: journald
  freeLocks: 2048
  hostname: anubis
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 7.2.5-200.fc44.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 119541760
  memTotal: 1977970688
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    defaultNetwork: podman
    dns:
      package: aardvark-dns-1.17.1-1.fc44.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.17.1
    package: netavark-1.17.2-1.fc44.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.17.2
  ociRuntime:
    name: crun
    package: crun-1.28-1.fc44.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.28
      commit: 54f16ffbefcd022bf032af768b5c5ce075c18bfc
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +JSON_C
  os: linux
  pasta:
                                                                                                                                                                                                              executable: /usr/bin/pasta
    package: passt-0^20260728.gf8df3f1-2.fc44.x86_64
    version: |
      pasta 0^20260728.gf8df3f1-2.fc44.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4293881856
  swapTotal: 4294963200
  uptime: 6h 16m 41.00s (Approximately 0.25 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  code.forgejo.org:
    Blocked: false
    Insecure: false
    Location: code.forgejo.org
    MirrorByDigestOnly: false
    Mirrors:
    - Insecure: false
      Location: harbor.tail444a1.ts.net/code.forgejo.org
      PullFromMirror: ""
    Prefix: code.forgejo.org
    PullFromMirror: ""
  codeberg.org:
    Blocked: false
    Insecure: false
    Location: codeberg.org
    MirrorByDigestOnly: false
    Mirrors:
    - Insecure: false
      Location: harbor.tail444a1.ts.net/codeberg.org
      PullFromMirror: ""
    Prefix: codeberg.org
    PullFromMirror: ""
  docker.io:
    Blocked: false
    Insecure: false
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors:
    - Insecure: false
      Location: harbor.tail444a1.ts.net/docker.io
      PullFromMirror: ""
    Prefix: docker.io
    PullFromMirror: ""
  ghcr.io:
    Blocked: false
    Insecure: false
    Location: ghcr.io
    MirrorByDigestOnly: false
    Mirrors:
    - Insecure: false
      Location: harbor.tail444a1.ts.net/ghcr.io
                                                                                                                                                                         PullFromMirror: ""
    Prefix: ghcr.io
    PullFromMirror: ""
  quay.io:
    Blocked: false
    Insecure: false
    Location: quay.io
    MirrorByDigestOnly: false
    Mirrors:
    - Insecure: false
      Location: harbor.tail444a1.ts.net/quay.io
      PullFromMirror: ""
    Prefix: quay.io
    PullFromMirror: ""
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /var/home/ram/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/ram/.local/share/containers/storage
  graphRootAllocated: 32681476096
  graphRootUsed: 11853742080
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /var/home/ram/.local/share/containers/storage/volumes
version:
  APIVersion: 5.8.7
  BuildOrigin: Fedora Project
  Built: 1789516800
  BuiltTime: Tue Sep 15 17:00:00 2026
  GitCommit: c593b672bf3db1173aebea565ebf1a724ea196dc
  GoVersion: go1.26.8-X:nodwarf5
  Os: linux
  OsArch: linux/amd64
  Version: 5.8.7
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Fedora bootc 44 (fedora-bootc:44 base). podman 5.8.4-1.fc44 with buildah 1.43.2 works; podman 5.8.7-1.fc44 with buildah 1.43.4 fails. The Fedora rebuild of the same image with the newer podman is the only change between the two.

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Honny1** [comment]
I tested this on Podman 6-dev with:

```bash
ctr=t-29805
podman rm -f "$ctr" 2>/dev/null || true
podman pull docker.io/library/node:26.9.0-trixie
# ----
podman run -d --rm --name "$ctr" docker.io/library/node:26.9.0-trixie sleep 120
tmpdir=$(mktemp -d)
echo hi >"$tmpdir/x"
tar -C "$tmpdir" --transform 's,^x,var/run/x,' -cf - x | podman cp - "$ctr:/"
podman exec "$ctr" cat /run/x   # expect: hi
# ----
podman rm -f -t0 "$ctr"
rm -rf "$tmpdir"
```

And it works. It seems that we should vendor buildah into podman 5.8. WDYT? @mheon @podman-container-tools/podman-maintainers

**Comment by mheon** [comment]
I don't think we can update Buildah in 5.8, we'd pull in the containers.conf breaking change? Unless you meant another patch.

**Comment by mtrmac** [comment]
@Honny1 AFAICT Podman’s `main` branch has not updated Buildah after https://github.com/podman-container-tools/buildah/security/advisories/GHSA-3528-5p26-cf44 ; this report suggests that either that security fix, or a related change , has been broken _on the stable branches_.

My guess is https://github.com/podman-container-tools/buildah/pull/7077 / https://github.com/podman-container-tools/buildah/pull/7081 , see the discussion in https://github.com/podman-container-tools/buildah/pull/7077#discussion_r3936389000 . The CVE fix used to contain a unit test that “absolute and escaping symbolic links are resolved relative to the root”, and that was removed because of these changes.
 
OTOH, to be fair, I spent a whole day trying to find a symlink reproducer where those changes actually break `podman cp`, and I couldn’t find one — ultimately `podman cp` seems to be doing its own symlink resolution of some kind. So I might very well be missing something.

**Comment by Honny1** [comment]
Well, I tested the reproducer with [podman#29789](https://github.com/podman-container-tools/podman/pull/29789) / Buildah `1.46.0-dev,` and it failed. It seems that we also need to fix buildah-main and then make backports. I tried to fix that with: https://github.com/podman-container-tools/buildah/pull/7129

**Comment by peppergrayxyz** [comment]
I ran into the same issue on `6.1.2` as report here: https://github.com/nektos/act/issues/6092#issuecomment-5794178677

```
$ https://github.com/meefik/linuxdeploy.git
$ cd linuxdeploy
$ act -j freebsd-build-and-test
INFO[0000] Using docker host 'unix:///run/user/1000/podman/podman.sock', and daemon socket 'unix:///run/user/1000/podman/podman.sock'
[CI/freebsd-build-and-test] ⭐ Run Set up job
[CI/freebsd-build-and-test] 🚀  Start image=catthehacker/ubuntu:full-latest
[CI/freebsd-build-and-test]   🐳  docker pull image=catthehacker/ubuntu:full-latest platform= username= forcePull=true
[CI/freebsd-build-and-test]   🐳  docker create image=catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[CI/freebsd-build-and-test]   🐳  docker run image=catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[CI/freebsd-build-and-test]   🐳  docker exec cmd=[chown -R 1001:1001 /home/pepper/dev/ghrepos/linuxdeploy] user=0 workdir=
[CI/freebsd-build-and-test]   🐳  docker exec cmd=[node --no-warnings -e console.log(process.execPath)] user= workdir=
[CI/freebsd-build-and-test]   ✅  Success - Set up job
[CI/freebsd-build-and-test]   ☁  git clone 'https://github.com/cross-platform-actions/action' # ref=v0.32.0
[CI/freebsd-build-and-test] ⭐ Run Main Repository checkout
[CI/freebsd-build-and-test]   🐳  docker cp src=/home/pepper/dev/ghrepos/linuxdeploy/. dst=/home/pepper/dev/ghrepos/linuxdeploy
[CI/freebsd-build-and-test]   🐳  docker exec cmd=[chown -R 1001:1001 /home/pepper/dev/ghrepos/linuxdeploy] user=0 workdir=
[CI/freebsd-build-and-test]   ✅  Success - Main Repository checkout [1.048135512s]
[CI/freebsd-build-and-test] ⭐ Run Main cross-platform-actions/action@v0.32.0
[CI/freebsd-build-and-test]   🐳  docker cp src=/home/pepper/.cache/act/cross-platform-actions-action@v0.32.0/ dst=/var/run/act/actions/cross-platform-actions-action@v0.32.0/
[CI/freebsd-build-and-test]   ❌  Failure - Main cross-platform-actions/action@v0.32.0 [733.242496ms]
[CI/freebsd-build-and-test] failed to copy content to container: Error response from daemon: statat var/run/act: path escapes from parent
[CI/freebsd-build-and-test] ⭐ Run Post cross-platform-actions/action@v0.32.0
[CI/freebsd-build-and-test]   🐳  docker exec cmd=[/usr/local/bin/node /var/run/act/actions/cross-platform-actions-action@v0.32.0/dist/post.mjs] user= workdir=
| node:internal/modules/cjs/loader:1210
|   throw err;
|   ^
|
| Error: Cannot find module '/var/run/act/actions/cross-platform-actions-action@v0.32.0/dist/post.mjs'
|     at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)
|     at Module._load (node:internal/modules/cjs/loader:1038:27)
|     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
|     at node:internal/main/run_main_module:28:49 {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: []
| }
|
| Node.js v20.20.0
[CI/freebsd-build-and-test]   ❌  Failure - Post cross-platform-actions/action@v0.32.0 [775.775426ms]
[CI/freebsd-build-and-test] exitcode '1': failure
[CI/freebsd-build-and-test] ⭐ Run Complete job
[CI/freebsd-build-and-test]   ✅  Success - Complete job
[CI/freebsd-build-and-test] 🏁  Job failed
Error: Error occurred running finally: exitcode '1': failure (original error: <nil>)
```
```
Trying to pull docker.io/catthehacker/ubuntu:full-latest...
Getting image source signatures
Copying blob ...
Copying config 8a6031f788 done   |
Writing manifest to image destination
ERRO[0069] statat var/run/act: path escapes from parent
```

The same thing works on `6.1.0`
